#!/bin/bash

# ==============================================================
#   ENHANCED SOCKS5 Proxy Auto-Install Script v2
#   With High Availability, Auto-Recovery & Monitoring
#   For Ubuntu VMs on GCP (Billionaires Technologies)
# ==============================================================

set -e

echo ""
echo "╔════════════════════════════════════════════════════════╗"
echo "║    SOCKS5 Proxy Installer v2 (HA-Enabled)             ║"
echo "║    Enhanced with Auto-Recovery & Health Monitoring    ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# ---- CONFIG (Modify if needed) ----
PROXY_USER="${PROXY_USER:-proxyuser}"
PROXY_PASS="${PROXY_PASS:-proxy@123}"
PROXY_PORT="${PROXY_PORT:-1080}"
# ------------------------------------

if [ "$EUID" -ne 0 ]; then
   echo "Error: This script must be run as root (use: sudo bash)"
   exit 1
fi

echo "[1/9] Updating system packages..."
apt update -y -q
apt upgrade -y -q

echo "[2/9] Installing dante-server and dependencies..."
apt install -y -q dante-server curl net-tools nano git

echo "[3/9] Creating proxy user..."
if id "$PROXY_USER" &>/dev/null; then
    echo "  User '$PROXY_USER' already exists, updating password..."
else
    useradd -r -s /bin/false "$PROXY_USER"
    echo "  User '$PROXY_USER' created."
fi
echo "$PROXY_USER:$PROXY_PASS" | chpasswd

echo "[4/9] Detecting network interface..."
INTERFACE=$(ip route | grep default | awk '{print $5}' | head -n1)
if [ -z "$INTERFACE" ]; then
    INTERFACE="eth0"
    echo "  Warning: Could not auto-detect interface, using eth0"
else
    echo "  Detected interface: $INTERFACE"
fi

echo "[5/9] Writing enhanced Dante configuration..."
# Backup old config if it exists
[ -f /etc/danted.conf ] && cp /etc/danted.conf /etc/danted.conf.bak.$(date +%s)

cat > /etc/danted.conf <<'EOF'
# ==============================================================
#   Dante SOCKS5 Configuration - Enhanced v2
#   Auto-generated by improved installer
# ==============================================================

# Single logoutput line (multiple entries on one line is valid)
logoutput: syslog /var/log/danted.log

# Listen on all interfaces
internal: 0.0.0.0 port = 1080

# Use VM's default outbound interface (replaced by installer)
external: eth0

# Require username/password auth — needed for Proxifier compatibility
socksmethod: username

clientmethod: none

user.privileged: root
user.notprivileged: nobody

# Connection limits and timeouts
maxchild: 10000
timeout.io: 600
timeout.connect: 30
timeout.negotiate: 30

# Client access rules
client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: connect disconnect error
}

# SOCKS5 rules — require username auth on all socks connections
socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    socksmethod: username
    protocol: tcp
    log: connect disconnect error
}

# Deny everything else
socks block {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: connect error
}
EOF

# Replace interface placeholder if needed
sed -i "s/external: eth0/external: ${INTERFACE}/" /etc/danted.conf
sed -i "s/port = 1080/port = ${PROXY_PORT}/" /etc/danted.conf

echo "  Config written: /etc/danted.conf"

echo "  Validating config syntax..."
if ! /usr/sbin/danted -V -f /etc/danted.conf 2>&1 | grep -q "dante"; then
    /usr/sbin/danted -V -f /etc/danted.conf || true
fi

echo "[5b/9] Opening firewall port ${PROXY_PORT}..."
if command -v ufw &>/dev/null && ufw status | grep -q "active"; then
    ufw allow "${PROXY_PORT}/tcp"
    echo "  UFW: port ${PROXY_PORT}/tcp opened"
else
    echo "  UFW not active — ensure GCP/cloud firewall allows TCP port ${PROXY_PORT} inbound"
fi

echo "[6/9] Installing High-Availability systemd service..."

cat > /etc/systemd/system/danted-ha.service <<'EOF'
[Unit]
Description=Dante SOCKS5 Proxy Server - High Availability
After=network.target
Wants=network-online.target

[Service]
Type=forking
PIDFile=/var/run/danted.pid
ExecStart=/usr/sbin/danted -D -p /var/run/danted.pid -f /etc/danted.conf
ExecReload=/bin/kill -HUP $MAINPID

# Auto-restart on any failure
Restart=always
RestartSec=5
StartLimitInterval=600
StartLimitBurst=10

User=root
Group=root

LimitNOFILE=65535
LimitNPROC=65535

StandardOutput=journal
StandardError=journal
SyslogIdentifier=danted

TimeoutStartSec=30
TimeoutStopSec=10

[Install]
WantedBy=multi-user.target
EOF

echo "  Service installed: danted-ha.service"

echo "[7/9] Installing Health Watchdog..."

cat > /usr/local/bin/proxy-watchdog.sh <<'WATCHDOG_EOF'
#!/bin/bash
set -u
PROXY_PORT="${1:-1080}"
CHECK_INTERVAL=60
LOGFILE="/var/log/proxy-watchdog.log"
MAX_RESTART_ATTEMPTS=3
RESTART_COOLDOWN=300
RESTART_COUNT=0
LAST_RESTART_TIME=0

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOGFILE"
}

is_process_running() {
    pgrep -x "danted" > /dev/null 2>&1
    return $?
}

is_port_listening() {
    netstat -tuln 2>/dev/null | grep -q ":${PROXY_PORT} " || ss -tuln 2>/dev/null | grep -q ":${PROXY_PORT} "
    return $?
}

test_proxy_connection() {
    timeout 5 bash -c "cat < /dev/null > /dev/tcp/localhost/${PROXY_PORT}" 2>/dev/null
    return $?
}

restart_proxy() {
    local now=$(date +%s)
    local time_since_restart=$((now - LAST_RESTART_TIME))
    
    if [ $RESTART_COUNT -ge $MAX_RESTART_ATTEMPTS ] && [ $time_since_restart -lt $RESTART_COOLDOWN ]; then
        log "ERROR: Too many restarts. Waiting..."
        return 1
    fi
    
    if [ $time_since_restart -ge $RESTART_COOLDOWN ]; then
        RESTART_COUNT=0
    fi
    
    log "WARNING: Proxy offline. Restarting (#$((RESTART_COUNT + 1)))..."
    systemctl restart danted-ha
    RESTART_COUNT=$((RESTART_COUNT + 1))
    LAST_RESTART_TIME=$now
    
    sleep 3
    
    if is_port_listening; then
        log "SUCCESS: Proxy restarted (port ${PROXY_PORT} listening)"
        return 0
    else
        log "ERROR: Restart failed"
        return 1
    fi
}

log "Starting Watchdog (Port: ${PROXY_PORT}, Interval: ${CHECK_INTERVAL}s)"

while true; do
    if ! is_process_running; then
        log "ALERT: Process not running"
        restart_proxy
    elif ! is_port_listening; then
        log "ALERT: Port not listening"
        restart_proxy
    elif ! test_proxy_connection; then
        log "ALERT: Connection failed"
        restart_proxy
    fi
    sleep "$CHECK_INTERVAL"
done
WATCHDOG_EOF

chmod +x /usr/local/bin/proxy-watchdog.sh
echo "  Watchdog installed: /usr/local/bin/proxy-watchdog.sh"

echo "[8/9] Installing Watchdog service..."

cat > /etc/systemd/system/proxy-watchdog.service <<EOF
[Unit]
Description=SOCKS5 Proxy Health Watchdog
After=network.target danted-ha.service
Requires=danted-ha.service

[Service]
Type=simple
ExecStart=/usr/local/bin/proxy-watchdog.sh ${PROXY_PORT}
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=proxy-watchdog

StartLimitInterval=300
StartLimitBurst=3

[Install]
WantedBy=multi-user.target
EOF

# Install status check script
cat > /usr/local/bin/proxy-status.sh <<'STATUS_EOF'
#!/bin/bash
PROXY_PORT="${1:-1080}"
echo ""
echo "╔════════════════════════════════════════════════════════╗"
echo "║       SOCKS5 Proxy Status & Health Check               ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

echo "[1] Process Status"
if pgrep -x "danted" > /dev/null; then
    PID=$(pgrep -x "danted")
    echo "    ✓ Process running (PID: $PID)"
else
    echo "    ✗ Process NOT running"
fi
echo ""

echo "[2] Port ${PROXY_PORT} Status"
if netstat -tuln 2>/dev/null | grep -q ":${PROXY_PORT} " || ss -tuln 2>/dev/null | grep -q ":${PROXY_PORT} "; then
    echo "    ✓ Port LISTENING"
else
    echo "    ✗ Port NOT listening"
fi
echo ""

echo "[3] Service Status"
systemctl is-active --quiet danted-ha && echo "    ✓ Service ACTIVE" || echo "    ✗ Service INACTIVE"
systemctl is-enabled --quiet danted-ha && echo "    ✓ Service ENABLED" || echo "    ✗ Service DISABLED"
echo ""

echo "[4] Watchdog Status"
pgrep -f "proxy-watchdog" > /dev/null && echo "    ✓ Watchdog running" || echo "    ✗ Watchdog NOT running"
echo ""

echo "╔════════════════════════════════════════════════════════╗"
if pgrep -x "danted" > /dev/null; then
    echo "║              STATUS: ✓ HEALTHY                        ║"
else
    echo "║              STATUS: ✗ OFFLINE                        ║"
fi
echo "╚════════════════════════════════════════════════════════╝"
echo ""
STATUS_EOF

chmod +x /usr/local/bin/proxy-status.sh
echo "  Status check installed: proxy-status.sh"

echo "[9/9] Enabling and starting services..."
systemctl daemon-reload
systemctl enable danted-ha
systemctl enable proxy-watchdog.service
systemctl restart danted-ha
sleep 2
systemctl start proxy-watchdog.service

# Create log directory
mkdir -p /var/log/proxy
touch /var/log/proxy-watchdog.log
chmod 666 /var/log/proxy-watchdog.log

# Wait for service to stabilize
sleep 3

# Final status check
echo ""
echo "╔════════════════════════════════════════════════════════╗"
echo "║       ✓ PROXY INSTALLATION COMPLETE (HA v2)           ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

EXTERNAL_IP=$(curl -s ifconfig.me 2>/dev/null || echo "Check GCP Console")

echo "PROXY DETAILS:"
echo "  External IP   : $EXTERNAL_IP"
echo "  Port          : ${PROXY_PORT}"
echo "  Username      : ${PROXY_USER}"
echo "  Password      : ${PROXY_PASS}"
echo "  Type          : SOCKS5"
echo ""
echo "PROXY CONNECTION STRING:"
echo "  socks5://${PROXY_USER}:${PROXY_PASS}@${EXTERNAL_IP}:${PROXY_PORT}"
echo ""

echo "SERVICES:"
echo "  Proxy Service    : systemctl status danted-ha"
echo "  Watchdog Service : systemctl status proxy-watchdog"
echo ""

echo "COMMANDS:"
echo "  Check Status    : proxy-status.sh"
echo "  View Logs       : tail -f /var/log/proxy-watchdog.log"
echo "  View Danted Log : tail -f /var/log/danted.log"
echo ""

echo "FEATURES:"
echo "  ✓ Auto-restart on crash (systemd)"
echo "  ✓ Health monitoring every 60 seconds"
echo "  ✓ Automatic recovery if port goes down"
echo "  ✓ Connection limits (prevents exhaustion)"
echo "  ✓ Timeout management (closes idle connections)"
echo "  ✓ Centralized logging"
echo "  ✓ Auto-start on VM reboot"
echo ""

echo "Next Steps:"
echo "  1. Verify proxy is working: proxy-status.sh"
echo "  2. Test from client: curl --proxy socks5://${PROXY_USER}:${PROXY_PASS}@${EXTERNAL_IP}:${PROXY_PORT} https://ifconfig.me"
echo "  3. Check logs if issues: tail -f /var/log/proxy-watchdog.log"
echo ""

# Show initial service status
echo "SERVICE STATUS:"
systemctl status danted-ha --no-pager | head -10
echo ""
systemctl status proxy-watchdog.service --no-pager | head -10
echo ""
